### ISSUE TITLE
css主题色跟随系统

### ISSUE THREAD

**Issue by TopAlien** [TopAlien/compatibility_issues#4]
详情： https://sanonz.github.io/2020/to-build-dark-and-light-theme-with-web/

```css
@media (prefers-color-scheme: dark) {
    body {
      color: #ccc;
      background-color: #1f1f1f;
    }
  }

@media (prefers-color-scheme: light) {
  body {
    color: #333;
    background-color: #eee;
  }
}

结合变量

:root {
  --color: #333;
  --bg-color: #eee;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color: #ccc;
    --bg-color: #1f1f1f;
  }
}

body {
  color: var(--color);
  background-color: var(--bg-color);
}
```
